# Generated by Django 5.1.7 on 2025-03-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Imagen')),
                ('tipo_detectado', models.CharField(max_length=100, verbose_name='Tipo Detectado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='imagenes/', verbose_name='Archivo de Imagen')),
            ],
        ),
    ]
